#服务端口
server:
  port: 8083
  #项目名称
spring:
  application:
    name: xunkeda
  #MySQL数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/xun_ke_da?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #thymeleaf配置文件
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false

  #热部署文件，页面不产生缓存，及时更新
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #mybatis文件配置
mybatis:
  # config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: debug